CREATE OR REPLACE FUNCTION C_REPLACE_PATH(P_PATH VARCHAR2) 
RETURN VARCHAR2 
AUTHID DEFINER -- OR AUTHID CURRENT_USER IF NEEDED
IS
BEGIN
    RETURN CASE 
        WHEN UPPER(P_PATH) LIKE 'K:\%' THEN 
            REPLACE(UPPER(P_PATH), 'K:\', '\\Abbotsford.loc\AppData\Amanda\')
        WHEN UPPER(P_PATH) LIKE '%\\FILESERVA\KOMMON%' THEN 
            REPLACE(UPPER(P_PATH), '\\FILESERVA\KOMMON', '\\Abbotsford.loc\AppData\Amanda')
        WHEN UPPER(P_PATH) LIKE '%\\FILESERVA\APPDATA\AMANDA%' THEN 
            REPLACE(UPPER(P_PATH), '\\FILESERVA\APPDATA\AMANDA', '\\Abbotsford.loc\AppData\Amanda')
        ELSE 
            P_PATH 
    END;
END;
/
COMMIT;