ALTER TRIGGER AMANDA.VALIDDOCUMENT_UPD DISABLE;

ALTER TRIGGER AMANDA.VALIDDOCUMENT_DEL DISABLE;

UPDATE AMANDA.VALIDDOCUMENT
SET
    MERGEDOCUMENT = C_REPLACE_PATH(MERGEDOCUMENT),
    SAVEPATH = C_REPLACE_PATH(SAVEPATH),
    TEMPPATH = C_REPLACE_PATH(TEMPPATH),
    SENDPATH = C_REPLACE_PATH(SENDPATH);

ALTER TRIGGER AMANDA.VALIDDOCUMENT_UPD ENABLE;

ALTER TRIGGER AMANDA.VALIDDOCUMENT_DEL ENABLE;


COMMIT;

select *
from AMANDA.VALIDDOCUMENT;


commit;