ALTER TRIGGER AMANDA.FOLDERDOCUMENT_UPD_LOG DISABLE;

ALTER TRIGGER AMANDA.FOLDERDOCUMENT_DEL_LOG DISABLE;

ALTER TRIGGER AMANDA.FOLDERDOCUMENT_DEL DISABLE;

UPDATE AMANDA.FOLDERDOCUMENT
SET DOSPATH = CASE
    WHEN UPPER(DOSPATH) LIKE UPPER('K:\%') THEN
        REPLACE(UPPER(DOSPATH), UPPER('K:\'), '\\ABBOTSFORD.LOC\APPDATA\AMANDA')
    WHEN UPPER(DOSPATH) LIKE UPPER('\\FILESERVA\KOMMON%') THEN
        REPLACE(UPPER(DOSPATH), UPPER('\\FILESERVA\KOMMON'), '\\ABBOTSFORD.LOC\APPDATA\AMANDA')
    WHEN UPPER(DOSPATH) LIKE UPPER('\\FILESERVA\APPDATA\AMANDA%') THEN
        REPLACE(UPPER(DOSPATH), UPPER('\\FILESERVA\APPDATA\AMANDA'), '\\ABBOTSFORD.LOC\APPDATA\AMANDA')
    ELSE
        DOSPATH
END
WHERE DOSPATH IS NOT NULL;


ALTER TRIGGER AMANDA.FOLDERDOCUMENT_UPD_LOG ENABLE;

ALTER TRIGGER AMANDA.FOLDERDOCUMENT_DEL_LOG ENABLE;

ALTER TRIGGER AMANDA.FOLDERDOCUMENT_DEL ENABLE;


commit;