ALTER TRIGGER AMANDA.ATTACHMENT_DEL_LOG DISABLE;

ALTER TRIGGER AMANDA.ATTACHMENT_UPD_LOG DISABLE;

ALTER TRIGGER AMANDA.ATTACHMENT_DEL DISABLE;

UPDATE AMANDA.ATTACHMENT
SET
    DOSPATH = _REPLACE_PATH(
        DOSPATH
    )
WHERE
    DOSPATH IS NOT NULL;

ALTER TRIGGER AMANDA.ATTACHMENT_DEL_LOG ENABLE;

ALTER TRIGGER AMANDA.ATTACHMENT_UPD_LOG ENABLE;

ALTER TRIGGER AMANDA.ATTACHMENT_DEL ENABLE;

COMMIT;

    