SHOW CON_NAME;


ALTER SESSION SET CONTAINER = A7TST;


SELECT FILE_NAME, TABLESPACE_NAME 
FROM DBA_DATA_FILES 
WHERE FILE_NAME = 'E:\APP\ORACLE\ORADATA\AMND17\A7DEV\AMANDA_TBS02.DBF';

ALTER DATABASE DATAFILE 'E:\APP\ORACLE\ORADATA\AMND17\A7DEV\AMANDA_TBS01.DBF' AUTOEXTEND ON NEXT 500M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE 'E:\APP\ORACLE\ORADATA\AMND17\A7DEV\AMANDA_TBS01.DBF' AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED;

ALTER DATABASE DATAFILE 'E:\APP\ORACLE\ORADATA\AMND17\A7DEV\AMANDA_TBS02.DBF' RESIZE 25000M;